### ISSUE TITLE
Hold to delete is also firing @cell-click and event-click

### ISSUE THREAD

**Issue by giulianimartini** [antoniandre/vue-cal-v4#296]
Hey,

I am having a little issue here.

When I use the vue-cal option @event-delete and hold to delete an event,
in a web browser, it fires the @event-click event also.
In mobile, it fires the @cell-click event.

I am using the @cell-click event to create a reservation and event-click to update a reservation in the vue-cal. So I can't remove a reservation without firing these other events.

How to prevent, when deleting an event, other events get fired?

Thanks.

**Comment by antoniandre** [comment]
Hi @giulianimartini,
Which version of Vue Cal are you using?
I believe this was fixed 10 days ago #287.

You can try on the documentation page as it is always the latest version:
https://antoniandre.github.io/vue-cal/#ex--emitted-events

Clear the logs after you focus an event then delete it.

Let me know if this is not fixed!

**Comment by giulianimartini** [comment]
Hey @antoniandre,

I am using the 3.4.1 version ("vue-cal": "^3.4.1" on package.json).

I have checked this thread [#287](https://github.com/antoniandre/vue-cal/issues/287) before posting here, but I am still facing the issue.

About the documentation, I'm always checking it. It's a really good documentation. So, maybe I missed something?

Here is my vue-cal instance code:

```
<vue-cal style="height: 100%"
    ref="vuecal"
    id="vuecal"
    :time-from="horarioAbertura === '' ? 6*60 : horarioAbertura"
    :time-to="horarioEncerramento === '' ? 24*60 : horarioEncerramento"
    :time-step="30"
    :disable-views="['years', 'year', 'month']"
    active-view="day"
    locale="pt-br"
    class="vuecal--full-height-delete"
    editable-events
    :events="res"
    :split-days="splitDays"
    :sticky-split-labels="stickySplitLabels"
    :min-cell-width="minCellWidth"
    :min-split-width="minSplitWidth"
    :time-cell-height="timeCellHeight"
    :selected-date="selectedDate"
    @ready="scrollToCurrentTime"
    :cell-click-hold="false"
    :on-event-click="onEventClick"
    @event-delete="removeReserva($event)"
    @cell-click="abreModalNovaReservaViaCalendario($event)">
</vue-cal>
```

If I use `@event-focus` instead of `:on-event-click`, I can't _click and hold_ to delete (of course).

My workaround was to use `@cell-dblclick`, but I am not sure about using this on production.

If you want any more details, please ask for :D

Thanks in advance.

**Comment by antoniandre** [comment]
Hi @giulianimartini, 
I misread, I thought you were saying that on delete it triggers the `cell-click` but you where talking about the event click & hold triggering `cell-click`.

I just released a fix for that: in version 3.5.1, any click on event will never bubble up to cell click. 
I think that's how it should be.

Also, even if not very important, the cell highlighting happens on mousedown now and not on click.

Let me know if that solves the issue.

**Comment by giulianimartini** [comment]
Hi @antoniandre,

That is exactly what I'm talking about. On the web-browser (chrome at least), it is working as expected, but on a webview (like I am using to develop for mobile), it is still firing the cell-click after deleting an event.

For now, I will use dblclick to create a reservation on my app, but would be great having it working on the cell-click (tap) also.

Thank you.

**Comment by giulianimartini** [comment]
@antoniandre 

I have found some new strange behaviours about clicking (touch) events on mobile devices.
I just searched on the documentation and have found nothing related to this issue.

In addition to those already reported about hold to delete, I am experiencing different actions getting triggered.

On mobile:
- `on-event-click`: if event is tapped, without release it, scroll down or up to any position of the calendar (draggable is set to false), fires the event-click.

I think the normal behaviour of `on-event-click` should be triggered only when the user released the click (tap) at the same position as starting the click (tap), or at least over the same event getting tapped.
As it is, scrolling the screen doesn't work properly (you would have to click on an empty cell or anywhere outside the calendar to scroll the screen).

- `on-event-dblclick`: fires the event double click only if the click (tap) is over the `title`. Nothing happen if the click is at any other position of the event.

On desktop, everything works as expected.

I am attaching two gifs to illustrate what is happening:

1. `on-event-click`:

![SVID_20200611_191621_1](https://user-images.githubusercontent.com/12451362/84445357-349c3100-ac1a-11ea-8db7-8edca10c3dc6.gif)

2. `on-event-dblclick`:

![SVID_20200611_193403_1](https://user-images.githubusercontent.com/12451362/84445980-f2272400-ac1a-11ea-9772-d454c6f47ff5.gif)

So, is there a fix for this issue?

Thanks in advance.

**Comment by giulianimartini** [comment]
Nothing?

**Comment by antoniandre** [comment]
Hi @giulianimartini, I'll have a look tonight

**Comment by giulianimartini** [comment]
Hi @antoniandre,

Thanks. 

Just a thing to note: on the event click and scroll down or up, besides firing the event click, it is not scrolling (this is the main issue, since double click is getting this behaviour too). Imagine that the calendar will be full of events during the days, so where the user will click to scroll?

Thank you again.

**Comment by antoniandre** [comment]
> on the event click and scroll down or up, it is not scrolling (this is the main issue, since double click is getting this behaviour too). Imagine that the calendar will be full of events during the days, so where the user will click to scroll?

The drag creation is not tailored for mobile and scrollable view at the same time, that's why there are  multiple options to create an event, the user can choose. 

It's also possible to have a button in your app to switch to creation mode that would disable the scroll while creating.

If you want to further discuss this matter please open a new issue.


___


Regarding the rest of the issue, I am doing some tests. It would be easier with your simplified code snippet though.

**Comment by giulianimartini** [comment]
Ok. I will open new issue about the scrolling.

Waiting for this :) 

Thank you.

**Comment by antoniandre** [comment]
I understand the second issue that triggers the event click when mouseup outside of event.
This is a complex case and requires more work, I will continue later.
What I have fixed in 3.5.5 is the fact that you could trigger the eventClick on first event when mousing up on a different event. This only solves a part of the problem.

**Comment by giulianimartini** [comment]
> Regarding the rest of the issue, I am doing some tests. It would be easier with your simplified code snippet though.

Sure, maybe this?

```
<vue-cal
    :disable-views="['years', 'year', 'month']"
    active-view="day"
    editable-events
    :events="[{start: '2020-06-17 14:00', end: '2020-06-17 17:30', title: 'Boring event',},{start: '2020-06-17 18:00', end: '2020-06-17 19:30', title: 'Boring event 2',}]"
    :cell-click-hold="false"
    :drag-to-create-event="false"
    :on-event-click="modalToUpdateEvent"
    @cell-click="modalToCreateEvent($event)">
</vue-cal>
```

1.`modalToUpdateEvent` opens a modal to update an existing event;
2.`modalToCreateEvent` opens a modal to create a new event.

The item 1 is being fired when the user clicks the event and scrolls to any position other than the event itself.

> What I have fixed in 3.5.5 is the fact that you could trigger the eventClick on first event when mousing up on a different event. This only solves a part of the problem.

Let me see if I understood this.

If I click upon on event and slide my finger (mobile here) upon another event and release the click, it will trigger the action of "event-click" for the first event clicked, right?

> I understand the second issue that triggers the event click when mouseup outside of event.
> This is a complex case and requires more work, I will continue later.

Yes. The right way, in my opinion, is just trigger the `event-click` if you release the click upon the same clicked event (never in any other position).

Thanks for taking care of this issue. I think it's really important.

**Comment by antoniandre** [comment]
Hi @giulianimartini, I am still working on this and #302.
Sorry about the delay but these are complex issues and need some serious testing and refactoring.
I have started a new branch for these 2 issues and it will take some time. Will let you know when fixed.

**Comment by giulianimartini** [comment]
Hi @antoniandre,

thank you for the feedback. I am waiting for this :D

**Comment by giulianimartini** [comment]
Hi @antoniandre,

After the 3.6.4 version of Vue-cal I am still facing the same problems.
After deleting the event, the `@cell-click` is being fired.

Do you have some news about this issue?

I am almost delivering the first version of my app and this is a thing that I cannot leave in the app.

A workaround for this is changing the way I delete an event. Maybe adding a button in the edit event modal will do the job, but I am fighting against this method, because the way Vue-cal handles the delete event is awesome, easy and fast.

Waiting for some feedback.

Thank you!

**Comment by giulianimartini** [comment]
Hi,

just to inform that I solved my problem of bubbling up after removing an event from vue-cal with a workaround based on setting a flag to know if the event propagation is coming from a reservation removal. If so, the cell-click event is not called, otherwise, the code follows the right flow.

Did this because event.stopPropagation() is not working as expected.

**Comment by antoniandre** [comment]
Thanks for the update @giulianimartini.
Sorry this refactoring is taking time I am very busy lately.
Will let you know when it's all good

**Comment by giulianimartini** [comment]
Hi @antoniandre,

No problem. For now, it is all ok. 
When you uptade, let me know. 

Thanks for the reply.

**Comment by antoniandre** [comment]
Hey @giulianimartini, 
I have fixed this in https://github.com/antoniandre/vue-cal/issues/322#issuecomment-686435786. 
The threshold is 30px, which allows shaky fingers to still trigger a click.

I ended up losing track of what the issue was in this thread as it's so big. lol
Please try and let me know if it works for you. 

Cheers.

**Comment by giulianimartini** [comment]
Hi @antoniandre,

thanks for this fix.

It is working as expected :D

Best Regards,
